# Generated by Django 4.1 on 2022-12-14 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="uploads/"
            ),
            preserve_default=False,
        ),
    ]
