# Generated by Django 4.1 on 2022-12-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="uploads/"),
        ),
    ]
